<?php
namespace AppBundle\Repository;

/**
 * TaskRepository
 *FunctionalityRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function findOpen($isDone)
	{
		return $this->findBy(['isDone' => $isDone]);
	}
}
